name: Build and deploy Firebase

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm ci
      - name: Render
        run: npm run prerender:fb
      - name: copy 404
        run: |
          cp dist/angularfire-doc/browser/404/index.html dist/angularfire-doc/browser/404.html
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULARFIRE_DOC }}'
          channelId: live
          projectId: angularfire-doc